name: Format

on:
    pull_request:
        branches: [ main ]
    push:

jobs:
    format:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        strategy:
            matrix:
                node-version: [18]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                version: 8
            
            - run: pnpm install --frozen-lockfile
            - run: pnpm run format
      
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: "format files"
